<a href="https://colab.research.google.com/github/prajudarekar04/College/blob/main/AIL310%20ML/Mobile_Plans.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Preprocessing Tools

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset

In [ ]:
dataset = pd.read_csv('Mobile_Plans.csv')  # Replace 'your_dataset.csv' with the actual file path
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print("X:")
print(X)

X:
[['Prepaid' 'Airtel' 2.5 249 15]
 ['Postpaid' 'Jio' 3.0 399 12]
 ['Prepaid' 'Vodafone Idea' 1.8 199 10]
 ['Postpaid' 'Airtel' 2.8 349 14]
 ['Prepaid' 'Jio' 2.2 249 13]
 ['Postpaid' 'Vodafone Idea' 3.5 449 11]
 ['Prepaid' 'Airtel' 2.0 199 12]
 ['Postpaid' 'Jio' 2.5 349 13]
 ['Prepaid' 'Vodafone Idea' 1.5 149 9]
 ['Postpaid' 'Airtel' 3.2 449 14]]


In [ ]:
print("y:")
print(y)

y:
['Affordable' 'Expensive' 'Affordable' 'Expensive' 'Affordable'
 'Expensive' 'Affordable' 'Expensive' 'Affordable' 'Expensive']


Encoding categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0, 1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print("X after encoding:")
print(X)

X after encoding:
[[0.0 1.0 1.0 0.0 0.0 2.5 249 15]
 [1.0 0.0 0.0 1.0 0.0 3.0 399 12]
 [0.0 1.0 0.0 0.0 1.0 1.8 199 10]
 [1.0 0.0 1.0 0.0 0.0 2.8 349 14]
 [0.0 1.0 0.0 1.0 0.0 2.2 249 13]
 [1.0 0.0 0.0 0.0 1.0 3.5 449 11]
 [0.0 1.0 1.0 0.0 0.0 2.0 199 12]
 [1.0 0.0 0.0 1.0 0.0 2.5 349 13]
 [0.0 1.0 0.0 0.0 1.0 1.5 149 9]
 [1.0 0.0 1.0 0.0 0.0 3.2 449 14]]


In [ ]:
print("y after encoding:")
print(y)

y after encoding:
[0 1 0 1 0 1 0 1 0 1]


Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [ ]:
print("X_train:")
print(X_train)

X_train:
[[0.0 1.0 1.0 0.0 0.0 2.0 199 12]
 [0.0 1.0 0.0 1.0 0.0 2.2 249 13]
 [0.0 1.0 1.0 0.0 0.0 2.5 249 15]
 [1.0 0.0 1.0 0.0 0.0 2.8 349 14]
 [1.0 0.0 0.0 1.0 0.0 3.0 399 12]
 [1.0 0.0 0.0 1.0 0.0 2.5 349 13]
 [0.0 1.0 0.0 0.0 1.0 1.5 149 9]
 [1.0 0.0 0.0 0.0 1.0 3.5 449 11]]


In [ ]:
print("X_test:")
print(X_test)

X_test:
[[0.0 1.0 0.0 0.0 1.0 1.8 199 10]
 [1.0 0.0 1.0 0.0 0.0 3.2 449 14]]


In [ ]:
print("y_train:")
print(y_train)

y_train:
[0 0 0 1 1 1 0 1]


In [ ]:
print("y_test:")
print(y_test)

y_test:
[0 1]


Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [ ]:
print("X_train after feature scaling:")
print(X_train)

X_train after feature scaling:
[[0.0 1.0 1.0 -0.7745966692414834 -0.5773502691896258 -0.8638684255813602
  -1.0327955589886446 -0.2170723815877265]
 [0.0 1.0 0.0 1.2909944487358056 -0.5773502691896258 -0.5183210553488158
  -0.5163977794943223 0.36178730264621084]
 [0.0 1.0 1.0 -0.7745966692414834 -0.5773502691896258 0.0
  -0.5163977794943223 1.5195066711140854]
 [1.0 0.0 1.0 -0.7745966692414834 -0.5773502691896258 0.5183210553488158
  0.5163977794943223 0.9406469868801481]
 [1.0 0.0 0.0 1.2909944487358056 -0.5773502691896258 0.8638684255813602
  1.0327955589886446 -0.2170723815877265]
 [1.0 0.0 0.0 1.2909944487358056 -0.5773502691896258 0.0
  0.5163977794943223 0.36178730264621084]
 [0.0 1.0 0.0 -0.7745966692414834 1.7320508075688774 -1.7277368511627205
  -1.5491933384829668 -1.9536514342895384]
 [1.0 0.0 0.0 -0.7745966692414834 1.7320508075688774 1.7277368511627205
  1.5491933384829668 -0.7959320658216638]]


In [ ]:
print("X_test after feature scaling:")
print(X_test)

X_test after feature scaling:
[[0.0 1.0 0.0 -0.7745966692414834 1.7320508075688774 -1.2094157958139042
  -1.0327955589886446 -1.374791750055601]
 [1.0 0.0 1.0 -0.7745966692414834 -0.5773502691896258 1.2094157958139047
  1.5491933384829668 0.9406469868801481]]
